version: '3'

volumes:
  mysql_data:
      driver: local
services:
  mysql:
      image: mysql:8.0.20
      volumes:
        - mysql_data:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: keycloak
        MYSQL_USER: keycloak
        MYSQL_PASSWORD: password
      ports:
        - "3309:3306"
      networks:
        - keycloak-network
  keycloak:
      image: jboss/keycloak:latest
      environment:
        DB_VENDOR: MYSQL
        DB_ADDR: mysql
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: password
        PROXY_ADDRESS_FORWARDING: "true"
        REDIRECT_SOCKET: "proxy-https"
        KEYCLOAK_FRONTEND_URL: "https://{your_domain}/auth"
      ports:
        - "8080:8080"
      networks:
        - keycloak-network
      depends_on:
        - mysql
  nginx:
      image: nginx
      container_name: nginx
      restart: on-failure
      volumes:
        - ./conf:/etc/nginx/conf.d
        - ./certs:/etc/nginx/certs
      ports:
        - "80:80"
        - "443:443"
      networks:
        - keycloak-network
      depends_on:
        - keycloak

networks:
  keycloak-network:
    external:
      name: keycloak-network
